spring:
  application:
    name: sharding-service
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

  client:
    service-url:
      defaultZone: http://localhost:9091/eureka/
server:
  port: 9097