spring:
  application:
    name: demo-consul
  cloud:
    consul:
      discovery:
        instance-id: consul01
        service-name: demo-consul
      host: localhost
      port: 8500

server:
  port: 9094
