spring:
  application:
    name: query-client-service
eureka:
  instance:
    hostname: client
    instance-id: ${spring.application.name}:${vcap.spring.application_id}:${spring.application.instance_id:${random.value}}

  client:
    service-url:
      defaultZone: http://localhost:9091/eureka/
server:
  port: 9092